### ISSUE TITLE
The hyperparameters to reproduce the experimental results

### ISSUE THREAD

**Issue by CKRE** [Guardianzc/DISCOpen-MedBox-DialoDiagnosis#2]
Hello,
We ran experiments with all datasets and methods, but the results were poor compared to the reported results.
Could you please share the hyperparameters corresponding to the experimental results?

**Comment by Guardianzc** [comment]
Most of the hyperparameters are listed in the model's readme, and here is some tips:
1. when training the HRL, you will need to adjust the number of groups to suit your needs and choose the appropriate experience_replay_size. In addition, the training of the HRL will take long before the rise because symptoms and diseases need to be trained simultaneously.
2. For the other models, we basically follow the original paper's  hyperparameters
